version: '2'

services:
   jenkins:
    image: 'h1kkan/jenkins-docker:2.319.3'
    container_name: dc-jenkins
    user: root
    ports:
      - '8282:8282'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - './jenkins-data:/var/jenkins_home'
    environment:
      - JENKINS_OPTS="--httpPort=8282"
      - JAVA_OPTS="-Duser.timezone=Europe/Madrid -Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP=\'default-src "self" "unsafe-inline" "unsafe-eval"; img-src "self" "unsafe-inline" data:; style-src "unsafe-inline";\'"
      - PIP_CONFIG_FILE=/var/jenkins_home/.pip/pip.conf
    restart: always


volumes:
  jenkins-data: {}
