---
version: "3.8"

services:
  uptime-kuda:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - uptime-kuma:/app/data
    ports:
      - "3001:3001"

volumes:
  uptime-kuma:
    driver: local
